package org.atriasoft.archidata.cron;

/**
 * Lifecycle listener for cron task executions, registered once via
 * {@link CronScheduler#setExecutionListener(CronExecutionListener)}.
 *
 * <p>{@link #onStart} is called by the consumer thread just before a task runs and returns an opaque
 * handle (generated by the implementation, e.g. a database id); the scheduler passes that same handle
 * back to {@link #onEnd} when the task finishes. Listener exceptions are caught and logged by the
 * scheduler, so a faulty listener never breaks task execution.
 */
public interface CronExecutionListener {
	/**
	 * Called before a task runs.
	 *
	 * @param taskName the task name
	 * @param trigger what caused this run
	 * @return an opaque handle passed back to {@link #onEnd}, or {@code null}
	 */
	Object onStart(String taskName, CronTriggerType trigger);

	/**
	 * Called after a task finished, whatever the outcome.
	 *
	 * @param handle the handle returned by the matching {@link #onStart}
	 * @param success {@code true} if the task ran without throwing, {@code false} otherwise
	 */
	void onEnd(Object handle, boolean success);

	/**
	 * Called after a task finished, with the failure cause when it threw. The scheduler catches
	 * {@link Throwable} around task execution (an {@link Error} such as {@code OutOfMemoryError} in a
	 * task must never kill the consumer thread), so {@code failure} can be any throwable, not only
	 * exceptions.
	 *
	 * <p>Default implementation delegates to {@link #onEnd(Object, boolean)} so existing listeners
	 * keep working unchanged; override this variant to record the failure itself (message, stack)
	 * in the execution journal.
	 *
	 * @param handle the handle returned by the matching {@link #onStart}
	 * @param success {@code true} if the task ran without throwing, {@code false} otherwise
	 * @param failure what the task threw, or {@code null} on success
	 */
	default void onEnd(final Object handle, final boolean success, final Throwable failure) {
		onEnd(handle, success);
	}
}
