package org.atriasoft.archidata.api;

import org.atriasoft.archidata.annotation.apiGenerator.ApiDoc;
import org.atriasoft.archidata.api.openApiResource;

import jakarta.annotation.security.PermitAll;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

/**
 * JAX-RS resource that serves an embedded Swagger UI page backed by the OpenAPI specification
 * generated by {@link openApiResource}.
 */
public class SwaggerUiExternal extends openApiResource {

	/**
	 * Returns an HTML page embedding the Swagger UI, configured to load the OpenAPI spec from the sibling endpoint.
	 * @return An HTML string containing the Swagger UI page.
	 */
	@GET
	@Produces(MediaType.TEXT_HTML)
	@PermitAll
	@ApiDoc(description = "Get the swagger UI", group = "DEVELOPEMENT")
	public String getSwaggerUI() {
		return """
				<!DOCTYPE html>
				<html lang="en">
				<head>
				    <meta charset="UTF-8">
				    <meta name="viewport" content="width=device-width, initial-scale=1.0">
				    <title>Swagger UI</title>
				    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.29.1/swagger-ui.css" />
				</head>
				<body>
				    <div id="swagger-ui"></div>
				    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.29.1/swagger-ui-bundle.js"></script>
				    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.29.1/swagger-ui-standalone-preset.js"></script>
				    <script>
				        window.onload = function() {
				            const ui = SwaggerUIBundle({
				                url: "openapi/swagger.json",
				                dom_id: '#swagger-ui',
				                presets: [
				                    SwaggerUIBundle.presets.apis,
				                    SwaggerUIStandalonePreset
				                ],
				                layout: 'BaseLayout',
				                deepLinking: true,
				            })
						}
				    </script>
				</body>
				</html>""";
	}
}
